services:
  bot:
    build: "."
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      BOT_ENV: ${BOT_ENV}
      CONTEXT: ${CONTEXT}
    volumes:
      - ./:/local_dir
  redis:
    image: redis/redis-stack-server:latest
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --appendfilename "embeddings.aof" --dir ./data --loglevel warning --requirepass "${REDIS_PASSWORD}" --loadmodule /opt/redis-stack/lib/redisearch.so --loadmodule /opt/redis-stack/lib/rejson.so
    volumes:
      - ./redis-volume:/data